version: "3"

services:
  nodewot:
    image: itaru2622/nodewot:bookworm
    container_name: nodewot
    hostname: nodewot
    environment:
       - http_proxy=${http_proxy}
       - https_proxy=${http_proxy}
       - no_proxy=${no_proxy}
    #volumes:
    ports:
        - "8888:8080/tcp"
        - "5683:5683/udp"
    #command: nodejs /opt/node-wot/packages/cli/dist/cli.js -h
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - http_proxy=${http_proxy}
        - https_proxy=${http_proxy}
        - no_proxy=${no_proxy}
        - REPO=${REPO:-https://github.com/eclipse/thingweb.node-wot.git -b master}
        - base=${base:-node:18-bookworm}
